//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chinook.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaylistTrack
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlaylistTrack()
        {
            this.PlaylistTrackHistories = new HashSet<PlaylistTrackHistory>();
        }
    
        public int PlaylistId { get; set; }
        public int TrackId { get; set; }
        public Nullable<bool> Dummy { get; set; }
    
        public virtual Playlist Playlist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlaylistTrackHistory> PlaylistTrackHistories { get; set; }
        public virtual Track Track { get; set; }
    }
}
