//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chinook.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaylistTrackHistory
    {
        public int PlaylistId { get; set; }
        public int TrackId { get; set; }
        public System.DateTime WrittenAt { get; set; }
    
        public virtual PlaylistTrack PlaylistTrack { get; set; }
    }
}
