// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using Chinook.Data;

namespace Chinook.Data
{
    public partial class ChinookContext
    {

        [DbFunction("GetSystemTime", "dbo")]
        public static DateTime? GetSystemTime()
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
