// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Chinook.Data;

public partial class PlaylistTrackHistory
{
    public int PlaylistId { get; set; }

    public int TrackId { get; set; }

    public DateTime WrittenAt { get; set; }

    public string Memo { get; set; }

    public virtual PlaylistTrack PlaylistTrack { get; set; }
}