// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hope.Data
{
    public partial class Action
    {
        /// <summary>
        /// 기능 아이디
        /// </summary>
        public int ActionId { get; set; }
        /// <summary>
        /// 기능 이름
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// 메모
        /// </summary>
        public string Memo { get; set; }
    }
}