// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hope.Data
{
    public partial class AlarmTalkTemplate
    {
        /// <summary>
        /// 세종텔레콤에 템플릿 등록하여 할당받은 코드
        /// </summary>
        public string TemplateCode { get; set; }
        /// <summary>
        /// 템플릿 이름, 세종텔레콤 등록 이름과 동일할 필요는 없음
        /// </summary>
        public string Title { get; set; }
        /// <summary>
        /// 고객에게 발송되는 템플릿 내용 (카카오 검수 필요)
        /// </summary>
        public string Contents { get; set; }
        /// <summary>
        /// 템플릿에 포함된 버튼에 표시되는 버튼이름
        /// </summary>
        public string ButtonName { get; set; }
        /// <summary>
        /// 버튼에 포함되는 URL 주소, 총 길이 200자 제한있음
        /// </summary>
        public string ButtonUrl { get; set; }
        /// <summary>
        /// 메모
        /// </summary>
        public string Memo { get; set; }
        /// <summary>
        /// 1이면 HOPE에서 선택가능하게 표시되고 0이면 표시되지 않음
        /// </summary>
        public bool Enabled { get; set; }
    }
}