// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hope.Data
{
    /// <summary>
    /// 배정 예약
    /// </summary>
    public partial class AssignmentReservation
    {
        public int CustomerId { get; set; }
        /// <summary>
        /// 예약일
        /// </summary>
        public DateTime AssigningOn { get; set; }
        public int UserId { get; set; }
        /// <summary>
        /// 예약 메모
        /// </summary>
        public string ReservationMemo { get; set; }

        public virtual Customer Customer { get; set; }
        public virtual User User { get; set; }
    }
}