// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hope.Data
{
    public partial class AssignmentGrade
    {
        /// <summary>
        /// [59] 고객 등급
        /// </summary>
        public int CustomerGradeCode { get; set; }
        public int Ratio { get; set; }
    }
}