// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hope.Data
{
    public partial class Assignment
    {
        /// <summary>
        /// 배정일
        /// </summary>
        public DateTime AssignedOn { get; set; }
        public int CustomerId { get; set; }
        public int UserId { get; set; }
        /// <summary>
        /// [58] 처리상태
        /// </summary>
        public int StatusCode { get; set; }
        /// <summary>
        /// 처리 메모
        /// </summary>
        public string Memo { get; set; }
        /// <summary>
        /// [80] 배정 유형
        /// </summary>
        public int TypeCode { get; set; }
        /// <summary>
        /// 배정 확인 일시
        /// </summary>
        public DateTime? PickedAt { get; set; }
        /// <summary>
        /// 예약 메모
        /// </summary>
        public string ReservationMemo { get; set; }
        /// <summary>
        /// 배정시 배정 예정일
        /// </summary>
        public DateTime? OriginalNextContactDate { get; set; }
        /// <summary>
        /// 처리상태 변경 일시
        /// </summary>
        public DateTime? StatusChangedAt { get; set; }

        public virtual Customer Customer { get; set; }
        public virtual User User { get; set; }
    }
}