// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hope.Data
{
    public partial class Attendance
    {
        /// <summary>
        /// 출결 일자
        /// </summary>
        public DateTime Date { get; set; }
        /// <summary>
        /// 직원코드
        /// </summary>
        public int UserId { get; set; }
        /// <summary>
        /// 특이사항
        /// </summary>
        public string Memo { get; set; }
        /// <summary>
        /// [4] 출근 상태
        /// </summary>
        public int StatusCode { get; set; }
        /// <summary>
        /// [5] 결근 특기
        /// </summary>
        public int AttributeCode { get; set; }
        /// <summary>
        /// CM근무일(콜)
        /// </summary>
        public decimal WorkDay { get; set; }
        /// <summary>
        /// 지각
        /// </summary>
        public bool IsLate { get; set; }

        public virtual User User { get; set; }
    }
}