// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hope.Data
{
    public partial class Audit
    {
        public int ConsultAuditId { get; set; }
        public int UserId { get; set; }
        /// <summary>
        /// ConsultId / CustomerId
        /// </summary>
        public int EntityId { get; set; }
        /// <summary>
        /// [75] 감사 유형
        /// </summary>
        public int TypeCode { get; set; }
        public DateTime At { get; set; }

        public virtual User User { get; set; }
    }
}