// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hope.Data
{
    public partial class Center
    {
        public Center()
        {
            CenterDepartments = new HashSet<CenterDepartment>();
            Users = new HashSet<User>();
        }

        public int CenterId { get; set; }
        public string Name { get; set; }
        public int? ChiefId { get; set; }
        public string Memo { get; set; }

        public virtual User Chief { get; set; }
        public virtual ICollection<CenterDepartment> CenterDepartments { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}