// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hope.Data
{
    public partial class CenterDepartment
    {
        public int CenterId { get; set; }
        public int DepartmentId { get; set; }
        public bool? Dummy { get; set; }

        public virtual Center Center { get; set; }
        public virtual Department Department { get; set; }
    }
}