// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hope.Data
{
    public partial class Chat
    {
        public int ChatId { get; set; }
        public int ConsultId { get; set; }
        public int ChatBy { get; set; }
        public int ChatTo { get; set; }
        public DateTime ChatAt { get; set; }
        public string Text { get; set; }
        /// <summary>
        /// 파일명 (이미지면 이미지 크기)
        /// </summary>
        public string FileName { get; set; }

        public virtual User ChatByNavigation { get; set; }
        public virtual User ChatToNavigation { get; set; }
        public virtual Consult Consult { get; set; }
    }
}