// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hope.Data
{
    /// <summary>
    /// 코드
    /// </summary>
    public partial class Code
    {
        /// <summary>
        /// 코드 아이디
        /// </summary>
        public int CodeId { get; set; }
        /// <summary>
        /// 코드 카테고리 아이디
        /// </summary>
        public int CodeCategoryId { get; set; }
        /// <summary>
        /// 비고
        /// </summary>
        public string Memo { get; set; }
        /// <summary>
        /// 시스템 코드
        /// </summary>
        public bool Enabled { get; set; }
        /// <summary>
        /// 텍스트
        /// </summary>
        public string Text { get; set; }

        public virtual CodeCategory CodeCategory { get; set; }
        public virtual CodeEx CodeEx { get; set; }
    }
}