// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hope.Data
{
    public partial class CodeEx
    {
        /// <summary>
        /// 코드 아이디
        /// </summary>
        public int CodeId { get; set; }
        /// <summary>
        /// 부가 정보
        /// </summary>
        public string AdditionalInfo { get; set; }

        public virtual Code Code { get; set; }
    }
}