// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hope.Data
{
    /// <summary>
    /// 코드 카테고리
    /// </summary>
    public partial class CodeCategory
    {
        public CodeCategory()
        {
            Codes = new HashSet<Code>();
        }

        /// <summary>
        /// 코드 카테고리 아이디
        /// </summary>
        public int CodeCategoryId { get; set; }
        /// <summary>
        /// 카테고리 이름
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// 비고
        /// </summary>
        public string Memo { get; set; }

        public virtual ICollection<Code> Codes { get; set; }
    }
}