// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hope.Data
{
    public partial class ColumnInfo
    {
        public string TableName { get; set; }
        public string ColumnName { get; set; }
        public string Type { get; set; }
        public bool IsNullable { get; set; }
        public int Position { get; set; }
        public bool? Active { get; set; }
        public string Memo { get; set; }
    }
}