// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hope.Data
{
    public partial class Consult
    {
        public Consult()
        {
            Chats = new HashSet<Chat>();
            Debts = new HashSet<Debt>();
            Homes = new HashSet<Home>();
            Incomes = new HashSet<Income>();
            ProductProgresses = new HashSet<ProductProgress>();
            Vehicles = new HashSet<Vehicle>();
            Works = new HashSet<Work>();
        }

        public int ConsultId { get; set; }
        public int CustomerId { get; set; }
        /// <summary>
        /// NICE 신용평가 점수
        /// </summary>
        public int? NiceScore { get; set; }
        /// <summary>
        /// 필요자금
        /// </summary>
        public string ForNecessity { get; set; }
        /// <summary>
        /// 대환
        /// </summary>
        public string ForTransfer { get; set; }
        public DateTime ModifiedAt { get; set; }
        public int ModifiedBy { get; set; }
        /// <summary>
        /// 고객정보 아카이브
        /// </summary>
        public string History { get; set; }
        /// <summary>
        /// 등록일
        /// </summary>
        public DateTime RegisteredOn { get; set; }
        /// <summary>
        /// 종결일
        /// </summary>
        public DateTime? ClosedOn { get; set; }
        /// <summary>
        /// 보험
        /// </summary>
        public bool HasInsurance { get; set; }
        /// <summary>
        /// 회파복
        /// </summary>
        public bool HasHoipabok { get; set; }
        /// <summary>
        /// 카드
        /// </summary>
        public bool HasCard { get; set; }
        /// <summary>
        /// 중복된 상담. 삭제해야 함
        /// </summary>
        public bool Duplicated { get; set; }

        public virtual Customer Customer { get; set; }
        public virtual User ModifiedByNavigation { get; set; }
        public virtual ICollection<Chat> Chats { get; set; }
        public virtual ICollection<Debt> Debts { get; set; }
        public virtual ICollection<Home> Homes { get; set; }
        public virtual ICollection<Income> Incomes { get; set; }
        public virtual ICollection<ProductProgress> ProductProgresses { get; set; }
        public virtual ICollection<Vehicle> Vehicles { get; set; }
        public virtual ICollection<Work> Works { get; set; }
    }
}