// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hope.Data
{
    public partial class CustomerMigration
    {
        public int CustomerId { get; set; }
        /// <summary>
        /// 구글파일
        /// </summary>
        public string SpreadName { get; set; }
        /// <summary>
        /// 구글시트
        /// </summary>
        public string SheetName { get; set; }
        /// <summary>
        /// 구글시트에서의 라인
        /// </summary>
        public int LineInSheet { get; set; }

        public virtual Customer Customer { get; set; }
    }
}