// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hope.Data
{
    /// <summary>
    /// 고객 첨부 파일
    /// </summary>
    public partial class CustomerFile
    {
        public int CustomerFileId { get; set; }
        public int CustomerId { get; set; }
        public int UploadedBy { get; set; }
        public DateTime UploadedAt { get; set; }
        /// <summary>
        /// 파일명 (이미지면 이미지 크기)
        /// </summary>
        public string FileName { get; set; }

        public virtual Customer Customer { get; set; }
        public virtual User UploadedByNavigation { get; set; }
    }
}