// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hope.Data
{
    /// <summary>
    /// 상담
    /// </summary>
    public partial class Customer
    {
        public Customer()
        {
            AssignmentReservations = new HashSet<AssignmentReservation>();
            Assignments = new HashSet<Assignment>();
            Consults = new HashSet<Consult>();
            CustomerFiles = new HashSet<CustomerFile>();
            CustomerHiddennesses = new HashSet<CustomerHiddenness>();
            CustomerMemos = new HashSet<CustomerMemo>();
            CustomerPasses = new HashSet<CustomerPass>();
            CustomerPermissions = new HashSet<CustomerPermission>();
            CustomerTags = new HashSet<CustomerTag>();
            Favorates = new HashSet<Favorate>();
            Memos = new HashSet<Memo>();
            Timers = new HashSet<Timer>();
        }

        public int CustomerId { get; set; }
        /// <summary>
        /// [59] 고객 등급
        /// </summary>
        public int CustomerGradeCode { get; set; }
        public DateTime ModifiedAt { get; set; }
        public int ModifiedBy { get; set; }
        /// <summary>
        /// 유니크한 값
        /// </summary>
        public string Telephone { get; set; }
        public string Name { get; set; }
        public DateTime? BirthDate { get; set; }
        /// <summary>
        /// [35] 성별
        /// </summary>
        public int GenderCode { get; set; }
        /// <summary>
        /// 배정 예정일
        /// </summary>
        public DateTime NextContactDate { get; set; }
        /// <summary>
        /// 전담 상담사
        /// </summary>
        public int? OwnerId { get; set; }
        public DateTime? RegisteredOn { get; set; }
        /// <summary>
        /// [40] 통신사
        /// </summary>
        public int PhoneCompanyCode { get; set; }
        /// <summary>
        /// [82] 고객 로그 타입
        /// </summary>
        public int LogTypeCode { get; set; }
        /// <summary>
        /// [74] 업무 유형 [58] 처리상태
        /// </summary>
        public int AdditionalCode { get; set; }

        public virtual User ModifiedByNavigation { get; set; }
        public virtual User Owner { get; set; }
        public virtual CustomerMigration CustomerMigration { get; set; }
        public virtual ICollection<AssignmentReservation> AssignmentReservations { get; set; }
        public virtual ICollection<Assignment> Assignments { get; set; }
        public virtual ICollection<Consult> Consults { get; set; }
        public virtual ICollection<CustomerFile> CustomerFiles { get; set; }
        public virtual ICollection<CustomerHiddenness> CustomerHiddennesses { get; set; }
        public virtual ICollection<CustomerMemo> CustomerMemos { get; set; }
        public virtual ICollection<CustomerPass> CustomerPasses { get; set; }
        public virtual ICollection<CustomerPermission> CustomerPermissions { get; set; }
        public virtual ICollection<CustomerTag> CustomerTags { get; set; }
        public virtual ICollection<Favorate> Favorates { get; set; }
        public virtual ICollection<Memo> Memos { get; set; }
        public virtual ICollection<Timer> Timers { get; set; }
    }
}