// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hope.Data
{
    public partial class CustomerTag
    {
        public int CustomerId { get; set; }
        public int UserId { get; set; }
        /// <summary>
        /// [78] 고객 태그
        /// </summary>
        public int TagCode { get; set; }

        public virtual Customer Customer { get; set; }
        public virtual User User { get; set; }
    }
}