// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hope.Data
{
    /// <summary>
    /// 고객 위임
    /// </summary>
    public partial class CustomerPass
    {
        public int CustomerPassId { get; set; }
        public int CustomerId { get; set; }
        public int PassedFrom { get; set; }
        public int? PassedTo { get; set; }
        public DateTime PassedAt { get; set; }
        /// <summary>
        /// [81] 연계 유형
        /// </summary>
        public int TypeCode { get; set; }

        public virtual Customer Customer { get; set; }
        public virtual User PassedFromNavigation { get; set; }
        public virtual User PassedToNavigation { get; set; }
    }
}