// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hope.Data
{
    public partial class Debt
    {
        public int DebtId { get; set; }
        public int ConsultId { get; set; }
        /// <summary>
        /// [73] 대출 유형
        /// </summary>
        public int TypeCode { get; set; }
        /// <summary>
        /// 금융사
        /// </summary>
        public string BankName { get; set; }
        /// <summary>
        /// 대출 원금
        /// </summary>
        public int Principal { get; set; }
        /// <summary>
        /// 기대출 잔액
        /// </summary>
        public int Remained { get; set; }
        /// <summary>
        /// 월 상환액
        /// </summary>
        public int MonthlyPayment { get; set; }
        /// <summary>
        /// 금리
        /// </summary>
        public decimal Rate { get; set; }
        /// <summary>
        /// 상환 기간(월)
        /// </summary>
        public int RepaymentPeriod { get; set; }
        public string Memo { get; set; }
        public int ModifiedBy { get; set; }
        public DateTime ModifiedAt { get; set; }
        /// <summary>
        /// 개설일 (NICE)
        /// </summary>
        public DateTime? OpenedOn { get; set; }
        /// <summary>
        /// 만기일 (NICE)
        /// </summary>
        public DateTime? ExpiredOn { get; set; }

        public virtual Consult Consult { get; set; }
    }
}