// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hope.Data
{
    public partial class Department
    {
        public Department()
        {
            CenterDepartments = new HashSet<CenterDepartment>();
            InverseParent = new HashSet<Department>();
            Users = new HashSet<User>();
        }

        public int DepartmentId { get; set; }
        public string Name { get; set; }
        public int? ManagerId { get; set; }
        public int? ParentId { get; set; }
        public string Memo { get; set; }

        public virtual User Manager { get; set; }
        public virtual Department Parent { get; set; }
        public virtual ICollection<CenterDepartment> CenterDepartments { get; set; }
        public virtual ICollection<Department> InverseParent { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}