// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hope.Data
{
    public partial class DocumentVersion
    {
        public int DocumentId { get; set; }
        public int Version { get; set; }
        public int Length { get; set; }
        public int UploadedBy { get; set; }
        public DateTime UploadedAt { get; set; }
        public string Memo { get; set; }

        public virtual Document Document { get; set; }
        public virtual User UploadedByNavigation { get; set; }
    }
}