// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hope.Data
{
    public partial class Favorate
    {
        public int UserId { get; set; }
        public int CustomerId { get; set; }
        public DateTime RegisteredAt { get; set; }

        public virtual Customer Customer { get; set; }
        public virtual User User { get; set; }
    }
}