// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hope.Data
{
    /// <summary>
    /// 범용 로그
    /// </summary>
    public partial class GenericLog
    {
        /// <summary>
        /// 범용 로그 아이디
        /// </summary>
        public int GenericLogId { get; set; }
        /// <summary>
        /// 사용자 아이디
        /// </summary>
        public int? UserId { get; set; }
        /// <summary>
        /// 사용자 이름
        /// </summary>
        public string UserName { get; set; }
        /// <summary>
        /// 로그 발생 시각
        /// </summary>
        public DateTime At { get; set; }
        /// <summary>
        /// 로그 메시지
        /// </summary>
        public string Message { get; set; }
        public string StackTrace { get; set; }
        public string Category { get; set; }

        public virtual User User { get; set; }
    }
}