// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hope.Data
{
    /// <summary>
    /// 토/일/양력 공휴일을 제외한 휴일
    /// </summary>
    public partial class Holiday
    {
        public DateTime Date { get; set; }
        public string Name { get; set; }
    }
}