// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hope.Data
{
    public partial class Memo
    {
        public int MemoId { get; set; }
        public int SenderId { get; set; }
        public int ReceiverId { get; set; }
        public DateTime SentAt { get; set; }
        public DateTime? ReadAt { get; set; }
        public string Content { get; set; }
        /// <summary>
        /// [12] 쪽지 유형
        /// </summary>
        public int TypeCode { get; set; }
        public int? CustomerId { get; set; }
        /// <summary>
        /// 파일명 (이미지면 이미지 크기)
        /// </summary>
        public string FileName { get; set; }

        public virtual Customer Customer { get; set; }
        public virtual User Sender { get; set; }
    }
}