// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hope.Data
{
    public partial class Menu
    {
        public Menu()
        {
            InverseParent = new HashSet<Menu>();
        }

        /// <summary>
        /// 메뉴 아이디
        /// </summary>
        public int MenuId { get; set; }
        /// <summary>
        /// 메뉴 컨테이너 아이디
        /// </summary>
        public int? ParentId { get; set; }
        /// <summary>
        /// 화면 표시 텍스트
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// 설명
        /// </summary>
        public string Memo { get; set; }
        /// <summary>
        /// 폼 클래스 이름
        /// </summary>
        public string FormClassName { get; set; }
        /// <summary>
        /// 폼 실행 타입 (9)
        /// </summary>
        public int FormTypeCode { get; set; }
        /// <summary>
        /// 폼 실행 매개변수
        /// </summary>
        public string FormArgument { get; set; }

        public virtual Menu Parent { get; set; }
        public virtual ICollection<Menu> InverseParent { get; set; }
    }
}