// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hope.Data
{
    public partial class OnlineRequest
    {
        public int OnlineRequestId { get; set; }
        /// <summary>
        /// 이벤트
        /// </summary>
        public string Event { get; set; }
        public string SafeKey { get; set; }
        public string Name { get; set; }
        public string Telephone { get; set; }
        public string Gender { get; set; }
        public DateTime BirthDate { get; set; }
        public string Job { get; set; }
        public string HouseInfo { get; set; }
        public string VehicleInfo { get; set; }
        public string CardInfo { get; set; }
        public DateTime RequestedAt { get; set; }
        /// <summary>
        /// 유입경로
        /// </summary>
        public string Origin { get; set; }
        /// <summary>
        /// 할당받은 CM
        /// </summary>
        public int? AllocatedTo { get; set; }
        /// <summary>
        /// 할당받은 시각
        /// </summary>
        public DateTime? AllocatedAt { get; set; }
        /// <summary>
        /// [62] 온라인 신청 처리상태
        /// </summary>
        public int StatusCode { get; set; }
        /// <summary>
        /// CM 처리일시
        /// </summary>
        public DateTime? ProcessedAt { get; set; }
        /// <summary>
        /// 광고 코드
        /// </summary>
        public string AdCode { get; set; }

        public virtual User AllocatedToNavigation { get; set; }
    }
}