// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hope.Data
{
    /// <summary>
    /// 퍼미션
    /// </summary>
    public partial class Permission
    {
        /// <summary>
        /// 역할 아이디
        /// </summary>
        public int RoleId { get; set; }
        /// <summary>
        /// 엔터티 아이디
        /// </summary>
        public int EntityId { get; set; }
        /// <summary>
        /// 퍼미션 타입
        /// </summary>
        public int PermissionTypeCode { get; set; }

        public virtual Role Role { get; set; }
    }
}