// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hope.Data
{
    public partial class ProductProgress
    {
        public int ProductProgressId { get; set; }
        public int ConsultId { get; set; }
        /// <summary>
        /// [21] 대출상품코드
        /// </summary>
        public int ProductCode { get; set; }
        /// <summary>
        /// [56] 금융사 처리상태
        /// </summary>
        public int StatusCode { get; set; }
        /// <summary>
        /// 금액
        /// </summary>
        public int Money { get; set; }
        /// <summary>
        /// 금리
        /// </summary>
        public decimal Rate { get; set; }
        public string Memo { get; set; }
        public int ModifiedBy { get; set; }
        public DateTime ModifiedAt { get; set; }
        /// <summary>
        /// 상환기간
        /// </summary>
        public int RepaymentPeriod { get; set; }
        /// <summary>
        /// 처리일시
        /// </summary>
        public DateTime ProcessedAt { get; set; }
        /// <summary>
        /// [77] 등급 코드
        /// </summary>
        public int GradeCode { get; set; }

        public virtual Consult Consult { get; set; }
        public virtual User ModifiedByNavigation { get; set; }
    }
}