// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hope.Data
{
    /// <summary>
    /// 푸시콜 녹음 파일 샷
    /// </summary>
    public partial class PushCallRecording
    {
        public int PushCallRecordingId { get; set; }
        public int UserId { get; set; }
        /// <summary>
        /// 샷을 찍은 일시
        /// </summary>
        public DateTime TakenAt { get; set; }
        /// <summary>
        /// 당일 업로드한 파일 갯수
        /// </summary>
        public int FileCount { get; set; }
        /// <summary>
        /// 마지막 녹음 파일의 생성 시각
        /// </summary>
        public DateTime LatestTime { get; set; }

        public virtual User User { get; set; }
    }
}