// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hope.Data
{
    public partial class Role
    {
        public Role()
        {
            Permissions = new HashSet<Permission>();
            UserRoles = new HashSet<UserRole>();
        }

        /// <summary>
        /// 역할 아이디
        /// </summary>
        public int RoleId { get; set; }
        /// <summary>
        /// 역할 이름
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// 메모
        /// </summary>
        public string Memo { get; set; }

        public virtual ICollection<Permission> Permissions { get; set; }
        public virtual ICollection<UserRole> UserRoles { get; set; }
    }
}