// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hope.Data
{
    public partial class Storage
    {
        public int EntityId { get; set; }
        public int SubEntityId { get; set; }
        /// <summary>
        /// [11] 첨부 파일 타입
        /// </summary>
        public int TypeCode { get; set; }
        public byte[] Binary { get; set; }
    }
}