// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hope.Data
{
    public partial class Support
    {
        /// <summary>
        /// 지원하는 스탭
        /// </summary>
        public int SupporterId { get; set; }
        /// <summary>
        /// 지원받는 CM
        /// </summary>
        public int SupporteeId { get; set; }
        /// <summary>
        /// [79] 지원 유형
        /// </summary>
        public int TypeCode { get; set; }

        public virtual User Supporter { get; set; }
    }
}