// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hope.Data
{
    public partial class Timer
    {
        public int TimerId { get; set; }
        public int CustomerId { get; set; }
        public int UserId { get; set; }
        public DateTime ScheduledAt { get; set; }
        public DateTime? ConfirmedAt { get; set; }
        public string Memo { get; set; }

        public virtual Customer Customer { get; set; }
        public virtual User User { get; set; }
    }
}