// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hope.Data
{
    public partial class UsbKeyLog
    {
        public int CodeId { get; set; }
        public DateTime CheckedAt { get; set; }
        public int UserId { get; set; }

        public virtual User User { get; set; }
    }
}