// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Hope.Data
{
    public partial class usp_GetUserLogResult
    {
        public int UserId { get; set; }
        public DateTime LoggedAt { get; set; }
        public string LogType { get; set; }
        public string LoginId { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public DateTime? Birthday { get; set; }
        public DateTime? DayIn { get; set; }
        public DateTime? DayOut { get; set; }
        public string Handphone { get; set; }
        public string Email { get; set; }
        public decimal GivenRestDay { get; set; }
        public int PermissionLevel { get; set; }
        public int DepartmentId { get; set; }
        public int GradeCode { get; set; }
        public bool Enabled { get; set; }
        public string Memo { get; set; }
        public DateTime? LastLoggedAt { get; set; }
        public string Sip { get; set; }
        public string SyncKey { get; set; }
        public string FcmToken { get; set; }
        public string BusinessHandphone { get; set; }
        public decimal LeftRestDay { get; set; }
        public decimal TakenRestDay { get; set; }
        public string AlarmTalkDivisionId { get; set; }
        public int BusinessPhoneCompanyCode { get; set; }
        public int CenterId { get; set; }
        public string KakaoSyncKey { get; set; }
        public bool IsSenior { get; set; }
        public DateTime LastPassedAt { get; set; }
        public int DailyPassQuota { get; set; }
        public int DailyAssignmentQuota { get; set; }
        public bool LessGradeOnly { get; set; }
    }
}
