// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Hope.Data
{
    public partial class usp_GetAttendanceLogResult
    {
        public DateTime Date { get; set; }
        public int UserId { get; set; }
        public DateTime LoggedAt { get; set; }
        public string LogType { get; set; }
        public string Memo { get; set; }
        public int StatusCode { get; set; }
        public int AttributeCode { get; set; }
        public decimal WorkDay { get; set; }
        public bool IsLate { get; set; }
    }
}
