// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Hope.Data
{
    public partial class usp_GetWorkLogResult
    {
        public int WorkId { get; set; }
        public DateTime LoggedAt { get; set; }
        public string LogType { get; set; }
        public int ConsultId { get; set; }
        public int UserId { get; set; }
        public DateTime RegisteredAt { get; set; }
        public string Memo { get; set; }
        public int TypeCode { get; set; }
        public int ModifiedBy { get; set; }
        public DateTime ModifiedAt { get; set; }
    }
}
