// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Hope.Data
{
    public partial class usp_GetCustomerLogResult
    {
        public int CustomerId { get; set; }
        public DateTime LoggedAt { get; set; }
        public string LogType { get; set; }
        public int CustomerGradeCode { get; set; }
        public DateTime ModifiedAt { get; set; }
        public int ModifiedBy { get; set; }
        public string Telephone { get; set; }
        public string Name { get; set; }
        public DateTime? BirthDate { get; set; }
        public int GenderCode { get; set; }
        public DateTime NextContactDate { get; set; }
        public int? OwnerId { get; set; }
        public DateTime? RegisteredOn { get; set; }
        public int PhoneCompanyCode { get; set; }
        public int LogTypeCode { get; set; }
        public int AdditionalCode { get; set; }
    }
}
