// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hope.Data
{
    public partial class Vehicle
    {
        public int VehicleId { get; set; }
        public int ConsultId { get; set; }
        /// <summary>
        /// [71] 차량소유형태
        /// </summary>
        public int CarOwnTypeCode { get; set; }
        /// <summary>
        /// [31] 차량할부형태
        /// </summary>
        public int CapitalLoanCode { get; set; }
        /// <summary>
        /// 차량연식
        /// </summary>
        public int ReleasedYear { get; set; }
        public string Memo { get; set; }
        public int ModifiedBy { get; set; }
        public DateTime ModifiedAt { get; set; }

        public virtual Consult Consult { get; set; }
    }
}