// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hope.Data
{
    /// <summary>
    /// 업무
    /// </summary>
    public partial class Work
    {
        public int WorkId { get; set; }
        public int ConsultId { get; set; }
        public int UserId { get; set; }
        public DateTime RegisteredAt { get; set; }
        public string Memo { get; set; }
        /// <summary>
        /// [74] 업무 유형
        /// </summary>
        public int TypeCode { get; set; }
        public int ModifiedBy { get; set; }
        public DateTime ModifiedAt { get; set; }

        public virtual Consult Consult { get; set; }
        public virtual User User { get; set; }
    }
}