// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Chinook.Data
{
    public partial class Employee
    {
        public Employee()
        {
            Customers = new HashSet<Customer>();
            InverseBoss = new HashSet<Employee>();
        }

        public int EmployeeId { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Title { get; set; }
        /// <summary>
        /// 보스
        /// </summary>
        public int? BossId { get; set; }
        public DateTime? HiredOn { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }

        public virtual Employee Boss { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<Employee> InverseBoss { get; set; }
    }
}