// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Chinook.Data
{
    public partial class usp_GeEmployeeRecursivelyResult
    {
        public int? EmployeeId { get; set; }
        public int? BossId { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Title { get; set; }
        public DateTime? HiredOn { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
    }
}
